# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
