# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161021_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='class_num',
            field=models.CharField(default=15, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='question',
            field=models.CharField(default='how to fish?', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
